apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnig-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ngnix-1
  template:
    metadata:
      labels:
        app: ngnix-1
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: ngnix-1
        ports:
        - containerPort: 80
